### ISSUE TITLE
List Compound and Aave tokens in the default token list

### ISSUE THREAD

**Issue by PaulRBerg** [safe-global/token-list#10]
## What is the feature about

It is common for on-chain treasuries to park their $USDC holdings into a lending protocol such as Compound or Aave.

## Feature request

Include Compound and Aave tokens in the "Default tokens" list. For example, the cUSDC v3 token on Mainnet:

https://etherscan.io/token/0xc3d688B66703497DAA19211EEdff47f25384cdc3

Our "Assets" page does not show our Compound deposit at the moment:

<img width="400" alt="SCR-20240403-nfhx" src="https://github.com/safe-global/safe-wallet-web/assets/8782666/c6c103f3-04f3-483e-b484-13ee9fafa45b">

**Comment by katspaugh** [comment]
@PaulRBerg thanks! I've moved your issue to this repo.

You can also make a pull request to this repo to add these tokens (here's an [example PR](https://github.com/safe-global/token-list/pull/5)). Otherwise we'll eventually add them ourselves, I've added this issue to the backlog.

Cheers!
